const pages=["home","courses","dashboard","login"];
function navTo(name){pages.forEach(p=>document.getElementById(p)?.classList.toggle("active-page",p===name));document.querySelectorAll("[data-nav]").forEach(x=>x.classList.toggle("active",x.dataset.nav===name));location.hash=name;scrollTo(0,0)}
document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=e=>{e.preventDefault();navTo(x.dataset.nav)});
const courses=[["Python for Beginners","Programming","Beginner","🐍","Learn Python fundamentals through practical mini projects."],["Web Development","Programming","Beginner","🌐","Build responsive websites using HTML, CSS and JavaScript."],["Data Science","Data Science","Intermediate","📊","Explore data analysis, visualization and practical insights."],["UI/UX Design","Design","Beginner","🎨","Learn user research, wireframes, visual design and usability."],["Machine Learning","Data Science","Intermediate","🤖","Understand supervised learning and predictive models."],["JavaScript Essentials","Programming","Beginner","⚡","Master core JavaScript concepts for interactive web apps."]];
const grid=document.getElementById("course-grid");
function render(filter=""){const f=filter.toLowerCase();grid.innerHTML=courses.filter(c=>(c[0]+" "+c[1]).toLowerCase().includes(f)).map(c=>`<article class="catalog-card"><div style="font-size:52px">${c[3]}</div><span class="tag">${c[1]}</span><h3>${c[0]}</h3><p>${c[4]}</p><small>${c[2]}</small><br><button class="small" data-course="${c[0]}">View Course →</button></article>`).join("")}
render();document.getElementById("search").oninput=e=>render(e.target.value);
document.addEventListener("click",e=>{const course=e.target.closest("[data-course]"),filter=e.target.closest("[data-filter]");if(course){const c=courses.find(x=>x[0]===course.dataset.course);document.getElementById("modal-content").innerHTML=`<div style="font-size:55px">${c[3]}</div><div class="eyebrow">${c[1]}</div><h2>${c[0]}</h2><p>${c[4]}</p><button class="primary" onclick="document.getElementById('modal').classList.remove('show');navTo('dashboard')">Enroll & Continue →</button>`;document.getElementById("modal").classList.add("show")}if(filter){navTo("courses");document.getElementById("search").value=filter.dataset.filter;render(filter.dataset.filter)}});
document.querySelector(".close").onclick=()=>document.getElementById("modal").classList.remove("show");
document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")e.currentTarget.classList.remove("show")};
document.getElementById("login-form").onsubmit=e=>{e.preventDefault();document.getElementById("login-msg").textContent="Demo login successful — welcome to EduLearn!";setTimeout(()=>navTo("dashboard"),700)};
const initial=location.hash.slice(1);if(pages.includes(initial))navTo(initial);